### ISSUE TITLE
Problem when importing

### ISSUE THREAD

**Issue by beckmx** [angularfy/ng-autonumeric#1]
I was trying to import it but looks like my project is suffering a little bit, it compiles correctly for angular4 but on runtime I get:

Unexpected value 'NgAutonumericModule' imported by the module ...

any suggestion?

**Comment by ainouss** [comment]
Hi, it is hard to tell without knowing the complete configuration.  are you using angular-cli ?

**Comment by beckmx** [comment]
nevermind, I took ur code and imported it locally, worked better that way

**Comment by ainouss** [comment]
Great then :)
