### ISSUE TITLE
issue with reactive forms

### ISSUE THREAD

**Issue by stepet80** [angularfy/ng-autonumeric#2]
Hello,

We are using this control with reactive forms (formControlName). We create a form and pass a value with the form control. Whenever we want to adapt the value through reactive forms by changing the value outside the user interface it doesn't seem to work. Could it be that there is still a problem with reactive forms?

In the code I can see that writeValue receives an object, but nothing is done with it...

`writeValue(obj: any): void {
    if (this.instance) {
      this.internal = this.instance.getFormatted();
    }
  }`

Kind regards,
Peters Stephan

**Comment by ainouss** [comment]
Hello,
Thanks for reporting this issue.

Yes, writeValue could be better implemented.  I'll see how to resolve this in future. I suggest you to to create an alias for the autonumeric instance in HTML and use the instance to update (visually) the value by using instance.set(myNewValue). 
I implemented a quick example in the planker bellow.

https://stackblitz.com/edit/ng-autonumeric-reactive-forms
Kind regards,

Abdelghani Ainouss

**Comment by stepet80** [comment]
Can you implement it in your library quicker ? The reason is that I work for a company with multiple teams and we want to implement this everywhere. I would like not to have to do that trick in every team :) We are talking about dozens of applications.

**Comment by ainouss** [comment]
Hello Stephan,
I will work on the issue for  the next release :). I was in a vacation and did not have time to update it. If you have any suggestion please feel free to send a merge request. Glad to know that it helps.
Kind regards,
Abdelghani.

**Comment by stepet80** [comment]
Ok thanks. No we don't have a suggestion for now.

**Comment by ainouss** [comment]
Support for reactive forms has been added, please upgrade to v 2.0.0

**Comment by Davide-a11y** [comment]
Hello!

With Angular 8.3.19 we encounter a problem when we try to dynamically update the value of the autonumeric field linked to a formcontrol field ( or linked to an ngModel ). You can see in this example https://stackblitz.com/edit/angular-wwld1p that in the ngOnInit the value is correctly setted, but in the onReset is not working properly: on the HTML element the value is setted, but if we print in the console the object, the value of the field is not changed...

Thanks!
Davide e Fabrizio
