### ISSUE TITLE
The form value is only updated when the user clicks away

### ISSUE THREAD

**Issue by gabrielstellini** [angularfy/ng-autonumeric#4]
## Expected Behavior
The form value should be updated whenever there's a change to the field

## Current Behavior
The form value is being updated whenever the user clicks away from the field.

## Possible Solution
An option in the directive which enables direct changes to the ngModel

## Steps to Reproduce
A demo of the issue can be found here: [Stackblitz](https://stackblitz.com/edit/ng-autonumeric-ja3bgl)
1. Modify the field.
2. Notice how the span is empty until you click away
3. Click away
4. Span gets updated with the input value

## Context (Environment)

I have a page with just 1 field (this autonumeric field). When the user enters a value, I need to:
1. Show an updated amount right below the field
2. Check validation of a button in a form and enable/disable accordingly

Since the ngModel is not updated with changes, from the user, there is no easy way to verify changes.

## Possible Implementation
Current:

    <input [ngAutonumeric]="{
    currencySymbol: '\u00a0€',
    minimumValue: '0'
    }" [(ngModel)]="myModel" (format)="onFormat($event)"/>

New:

    <input [ngAutonumeric]="{currencySymbol: '\u00a0€', minimumValue: '0'}"
    updateOnChanges
    [(ngModel)]="myModel" (format)="onFormat($event)"/>

**Comment by ainouss** [comment]
Hello Gabriel,

Thanks for reporting this issue.

It has been fixed in version 2.1.0
